### PR TITLE
LH-73626: Generate CDO SDK for Python on every merge to master

### PR DESCRIPTION
**Pull request by hazital**
https://jira-eng-rtp3.cisco.com/jira/browse/LH-73626

this one uses `openapi-generator` to generate python SDK for CDO.

### CODE REVIEW

**Review by weilueluo — COMMENTED** [review]
Do we want to setup github ci to publish to pip automatically on changes to `openapi.yaml`?

**Comment by hazital** [comment]
> Do we want to setup github ci to publish to pip automatically on changes to `openapi.yaml`?

yes, this one currently doesn't publish to pip and only generates the SDK 
we can provide a repo to pip and based on that, publish the new pkg/version, this will be the next step

**Review by weilueluo — APPROVED** [review]
LGTM! Only reviewed the `download_command.sh`, I suppose the rest is generated

**Review by siddhuwarrier — CHANGES_REQUESTED** [review]
Please no mixing github acitons and jenkinsfile; this should be part of the platform jenkins run, which is where we run the other stuff

**Comment by hazital** [comment]
> Please no mixing github acitons and jenkinsfile; this should be part of the platform jenkins run, which is where we run the other stuff

Thanks, I've ignored the generation of that file

**Review by siddhuwarrier — APPROVED** [review]

**Pull request merged**
